language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py27-pyramid13
  - TOX_ENV=py27-pyramid14
  - TOX_ENV=py27-pyramid15
  - TOX_ENV=py27-pyramid16
  - TOX_ENV=py27-pyramid17
  - TOX_ENV=py34
  - TOX_ENV=py34-pyramid15
  - TOX_ENV=py34-pyramid16
  - TOX_ENV=py34-pyramid17
  - TOX_ENV=py35
  - TOX_ENV=py35-pyramid15
  - TOX_ENV=py35-pyramid16
  - TOX_ENV=py35-pyramid17
  - TOX_ENV=py36
  - TOX_ENV=py36-pyramid15
  - TOX_ENV=py36-pyramid16
  - TOX_ENV=py36-pyramid17
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
