---
name: "CI"

on:
  push:
  schedule:
    - cron: '10 3 * * 1'

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            os: "ubuntu-latest"
          - python-version: "3.8"
            os: "ubuntu-latest"
          - python-version: "3.9"
            os: "ubuntu-latest"
          - python-version: "3.10"
            os: "ubuntu-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel tox
      - name: "Run tox targets for ${{ matrix.project }} with Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v --skip-missing-interpreters -- -v
